# Generated by Django 5.2.6 on 2025-09-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardealing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='includes',
        ),
        migrations.RemoveField(
            model_name='service',
            name='requirements',
        ),
    ]
