# Generated by Django 5.2.6 on 2025-09-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardealing', '0002_remove_service_includes_remove_service_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='max_year',
        ),
        migrations.RemoveField(
            model_name='service',
            name='min_year',
        ),
        migrations.RemoveField(
            model_name='service',
            name='supported_fuel_types',
        ),
        migrations.RemoveField(
            model_name='service',
            name='supported_makes',
        ),
    ]
