# Generated by Django 5.2.6 on 2025-09-30 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealing', '0003_remove_service_max_year_remove_service_min_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Morning Shift, Evening Shift', max_length=100)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.PositiveIntegerField(default=60, help_text='Slot duration in minutes')),
                ('slots_per_session', models.PositiveIntegerField(default=1, help_text='Number of concurrent slots')),
                ('buffer_between_slots', models.PositiveIntegerField(default=15, help_text='Buffer time between slots in minutes')),
                ('total_capacity', models.PositiveIntegerField(default=1)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slot Template',
                'verbose_name_plural': 'Slot Templates',
                'db_table': 'slot_templates',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.RemoveIndex(
            model_name='serviceslot',
            name='service_slo_externa_7ee59f_idx',
        ),
        migrations.AddField(
            model_name='serviceslot',
            name='generation_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='serviceslot',
            name='is_generated_from_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AddField(
            model_name='slottemplate',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_templates', to='cardealing.service'),
        ),
        migrations.AddField(
            model_name='serviceslot',
            name='slot_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_slots', to='cardealing.slottemplate'),
        ),
        migrations.AddIndex(
            model_name='serviceslot',
            index=models.Index(fields=['slot_template'], name='service_slo_slot_te_ccbb92_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceslot',
            index=models.Index(fields=['is_generated_from_template'], name='service_slo_is_gene_5baf0e_idx'),
        ),
    ]
