# Generated by Django 5.2.6 on 2025-10-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealing', '0005_availableslot_alter_serviceslot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=19, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=19, max_digits=20, null=True),
        ),
    ]
