# Generated by Django 5.2.6 on 2025-10-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealing', '0005_availableslot_alter_serviceslot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerprofile',
            name='business_hours',
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS Latitude', null=True),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS Longitude', null=True),
        ),
    ]
