# Generated by Django 5.2.5 on 2025-09-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_remove_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('dealer', 'Dealer'), ('admin', 'Administrator')], default='customer', max_length=20),
        ),
    ]
